Repository SOPT-all/35-COLLABORATION-ANDROID-KORAILTALK, pull requests merged in 2024-11, with the labels that each got.

#4 [Setting/#3] Design System 세팅
  app/src/main/java/com/sopt/korailtalk/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/korailtalk/ui/theme/Color.kt
  app/src/main/java/com/sopt/korailtalk/ui/theme/Theme.kt
  app/src/main/java/com/sopt/korailtalk/ui/theme/Type.kt
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: ⚙ Setting, ✨ 수현

#6 [Chore/#5] Design System 변수명 및 함수명 변경
  app/src/main/java/com/sopt/korailtalk/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/korailtalk/ui/theme/Color.kt
  app/src/main/java/com/sopt/korailtalk/ui/theme/Theme.kt
Labels: ❤️‍🩹 Chore, ✨ 수현

#10 [Feat/#9] SeatMap, TrainCheck, 공통 컴포넌트 구현
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailDialog.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailTicketHeader.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailWayInfo.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailWayInfoWithTime.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/component/SeatMapCoachSelector.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/component/SeatMapSeatSelector.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/component/TrainCheckDetailInfo.kt
  app/src/main/res/drawable/ic_arrow_circle.xml
  app/src/main/res/drawable/ic_money.xml
  app/src/main/res/drawable/ic_seatmap_backward_activate.xml
  app/src/main/res/drawable/ic_seatmap_backward_inactive.xml
  app/src/main/res/drawable/ic_seatmap_backward_selected.xml
  app/src/main/res/drawable/ic_seatmap_forward_activate.xml
  app/src/main/res/drawable/ic_seatmap_forward_inactive.xml
  app/src/main/res/drawable/ic_seatmap_forward_selected.xml
  app/src/main/res/drawable/ic_traincheck_passenger.xml
  app/src/main/res/drawable/ic_traincheck_seat.xml
  app/src/main/res/drawable/img_outlet.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🤢 태정

#13 [Feat/#8] "열차조회 뷰", "나의 티켓 뷰" 컴포넌트 제작 및 공통 컴포넌트 제작
  app/src/main/java/com/sopt/korailtalk/domain/type/MyTicketButtonType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/MyTicketTabType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/SearchTrainType.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailBottomSheet.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailChip.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailOptionBottomSheetItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/MyTicketScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketAdditionalService.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketButton.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketInfoItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketTabBar.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TrainSearchScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchDepartureToArrival.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchFilterItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainDateChip.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainFilter.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchWayInfoWithTravelTime.kt
  app/src/main/res/drawable/ic_arrow_blue_right.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_close_black.xml
  app/src/main/res/drawable/ic_search_arrow_down.xml
  app/src/main/res/drawable/ic_search_arrow_right.xml
  app/src/main/res/drawable/ic_search_triangle_down.xml
  app/src/main/res/drawable/ic_ticket_help.xml
  app/src/main/res/drawable/ic_ticket_refresh_l.xml
  app/src/main/res/drawable/ic_ticket_report.xml
  app/src/main/res/drawable/ic_ticket_sms.xml
  app/src/main/res/drawable/img_ticket_qr.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ✨ 수현

#19 [Feat/#12,#17] "좌석 조회 뷰", "승차권 확인 뷰" UI 구현
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/TicketResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailDialog.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailTicketHeader.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailWayInfo.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailWayInfoWithTime.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatMapData.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatMapScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatMapViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/component/SeatMapCoachSelector.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/component/SeatMapSeatSelector.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/TrainCheckScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/TrainCheckViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/component/TrainCheckDetailInfo.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/component/TrainCheckDialogContent.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/component/TrainCheckNotice.kt
  app/src/main/res/drawable/ic_seat_direction.xml
  app/src/main/res/drawable/ic_seatmap_backward.xml
  app/src/main/res/drawable/ic_seatmap_consent.xml
  app/src/main/res/drawable/ic_seatmap_forward.xml
  app/src/main/res/drawable/ic_seatmap_none.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🤢 태정

#18 [Feat/#16] "나의 티켓 뷰" UI 구현
  app/build.gradle.kts
  app/src/main/assets/and_korail.json
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailWayInfoWithTime.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/MyTicketScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/MyTicketViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicket.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketInfoItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketNotificationBar.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketToast.kt
  app/src/main/res/drawable/ic_ticket_share.xml
  app/src/main/res/drawable/img_ticket_bg.xml
  gradle/libs.versions.toml
Labels: ✨ Feat, ✨ 수현

#20 [Feat/#14] "열차조회 뷰" UI 구현
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/TrainSearchResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/TrainInformation.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/CarType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/SearchCarType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/SearchTrainStateType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/SearchTrainType.kt
  app/src/main/java/com/sopt/korailtalk/domain/type/SearchWayType.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailBottomSheet.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/KorailOptionBottomSheetItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TrainSearchScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TravelSearchViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchDetailBottomSheet.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchFilterItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainDateChip.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainFilter.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainInfoItem.kt
  app/src/main/res/drawable/ic_search_arrow_up.xml
  app/src/main/res/drawable/ic_search_money.xml
  app/src/main/res/drawable/ic_search_soldout.xml
  app/src/main/res/drawable/ic_search_timetable.xml
  app/src/main/res/drawable/ic_search_triangle_up.xml
  app/src/main/res/drawable/img_search_moneytable.xml
  app/src/main/res/drawable/img_search_timetable.xml
Labels: ✨ Feat, ✨ 수현

#24 [Feat/#23] "좌석 선택 뷰", "승차권 확인 뷰" 서버통신 구현
  app/src/main/java/com/sopt/korailtalk/data/mapper/todata/SeatSelectingMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/mapper/todomain/LeftSeatsResponseMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/mapper/todomain/TicketResponseMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasource/SeatsRemoteDataSource.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasource/TicketRemoteDataSource.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasourceimpl/SeatsRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasourceimpl/TicketRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/base/ApiResponse.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/request/SeatSelectingRequestDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/LeftSeatsResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/SeatTicketResponse.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/TicketResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/service/SeatsService.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/service/TicketService.kt
  app/src/main/java/com/sopt/korailtalk/data/repositoryimpl/SeatsRepositoryImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/repositoryimpl/TicketRepositoryImpl.kt
  app/src/main/java/com/sopt/korailtalk/di/DataSourceModule.kt
  app/src/main/java/com/sopt/korailtalk/di/NetworkModule.kt
  app/src/main/java/com/sopt/korailtalk/di/RepositoryModule.kt
  app/src/main/java/com/sopt/korailtalk/di/ServiceModule.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/LeftSeats.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/SeatSelecting.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/SeatTicket.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/TicketData.kt
  app/src/main/java/com/sopt/korailtalk/domain/repository/SeatsRepository.kt
  app/src/main/java/com/sopt/korailtalk/domain/repository/TicketRepository.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/MyTicketViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicket.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/myticket/component/MyTicketInfoItem.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/LeftSeatsState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatMapScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatMapViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/seatmap/SeatSelectingState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/TicketState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/TrainCheckScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/traincheck/TrainCheckViewModel.kt
Labels: ✨ Feat, 🤢 태정

#25 [Feat/#21] "열차조회 뷰" api 연동
  app/src/main/java/com/sopt/korailtalk/data/mapper/todata/TicketBuyingMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/mapper/todomain/LPointResponseDtoMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/mapper/todomain/TrainSearchResponseDtoMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasource/PaymentRemoteDataSource.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasource/TrainSearchRemoteDataSource.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasourceimpl/PaymentRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasourceimpl/TrainSearchRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/base/ApiResponse.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/request/TicketBuyingRequestDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/LPointResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/TrainSearchResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/service/PaymentService.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/service/TrainSearchService.kt
  app/src/main/java/com/sopt/korailtalk/data/repositoryimpl/PaymentRepositoryImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/repositoryimpl/TrainSearchRepositoryImpl.kt
  app/src/main/java/com/sopt/korailtalk/di/DataSourceModule.kt
  app/src/main/java/com/sopt/korailtalk/di/RepositoryModule.kt
  app/src/main/java/com/sopt/korailtalk/di/ServiceModule.kt
  app/src/main/java/com/sopt/korailtalk/di/qualifier/Qualifier.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/LPoint.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/TicketBuying.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/TimeTable.kt
  app/src/main/java/com/sopt/korailtalk/domain/repository/PaymentRepository.kt
  app/src/main/java/com/sopt/korailtalk/domain/repository/TrainSearchRepository.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/LPointState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/PaymentScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/TicketBuyingState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/component/PaymentTextField.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TimeTableState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TrainSearchScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/TravelSearchViewModel.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchDetailBottomSheet.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/trainsearch/component/SearchTrainInfoItem.kt
  app/src/main/res/drawable/ic_payment_privacy_not_selected.xml
  app/src/main/res/drawable/ic_payment_privacy_selected.xml
Labels: ✨ Feat, ✨ 수현

#22 [Feat/#15] "결제하기 뷰" UI 구현 및 서버통신 구현
  app/src/main/java/com/sopt/korailtalk/data/mapper/todata/TicketBuyingMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/mapper/todomain/LPointResponseDtoMapper.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasource/PaymentRemoteDataSource.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/datasourceimpl/PaymentRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/request/TicketBuyingRequestDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/model/response/LPointResponseDto.kt
  app/src/main/java/com/sopt/korailtalk/data/remote/service/PaymentService.kt
  app/src/main/java/com/sopt/korailtalk/data/repositoryimpl/PaymentRepositoryImpl.kt
  app/src/main/java/com/sopt/korailtalk/di/DataSourceModule.kt
  app/src/main/java/com/sopt/korailtalk/di/NetworkModule.kt
  app/src/main/java/com/sopt/korailtalk/di/RepositoryModule.kt
  app/src/main/java/com/sopt/korailtalk/di/ServiceModule.kt
  app/src/main/java/com/sopt/korailtalk/di/qualifier/Qualifier.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/LPoint.kt
  app/src/main/java/com/sopt/korailtalk/domain/model/TicketBuying.kt
  app/src/main/java/com/sopt/korailtalk/domain/repository/PaymentRepository.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/LPointState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/PaymentScreen.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/TicketBuyingState.kt
  app/src/main/java/com/sopt/korailtalk/presentation/ui/payment/component/PaymentTextField.kt
  app/src/main/res/drawable/ic_payment_privacy_not_selected.xml
  app/src/main/res/drawable/ic_payment_privacy_selected.xml
Labels: ✨ Feat, ✋ 민재
